sudo: required

language: java

jdk:
  - openjdk8

env:
  - MAV_OPT=--batch-mode

install:
  - echo start install
  - mvn ${MAV_OPT} install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - echo start build
  - mvn ${MAV_OPT} clean package -Pprovided

after_script:
  - echo Build completed on `date`
